Duration<-read.delim('/var/www/cgi-bin/bugpandata/Duration.txt',header=TRUE)
names(Duration)<-c("Starttimes","Endtimes","Duration","Values")
DurationStartTimes<-data.matrix(Duration[1])
DurationEndTimes<-data.matrix(Duration[2])
DurationReal<-data.matrix(Duration[3])
DurationValues<-data.matrix(Duration[4])
require(Cairo)
CairoPNG("/var/www/cgi-bin/bugpandata/DurationStartTime.png")
hist(DurationStartTimes,col="BurlyWood",50,xlab="displacedAngle Start Times")
dev.off()
CairoPNG(width=280,height=325,"/var/www/cgi-bin/bugpandata/DurationEndTime.png")
hist(DurationEndTimes,col="IndianRed",50,xlab="displacedAngle End Times")
dev.off()
CairoPNG(width=280,height=325,"/var/www/cgi-bin/bugpandata/Duration.png")
hist(DurationReal,col="yellow",xlab="Duration of displacedAngle",50)
dev.off()
CairoPNG(width=280,height=325,"/var/www/cgi-bin/bugpandata/DurationValues.png")
hist(DurationValues,50,col="brown",xlab="Values associated with displacedAngle")
dev.off()
CairoPNG(width=280,height=325,"/var/www/cgi-bin/bugpandata/durationxyscatter.png")
plot(DurationEndTimes~DurationStartTimes,data=Duration,col="GoldenRod")
title(main="Scatter Plot for start and end times")
abline(lm(DurationEndTimes~DurationStartTimes,data=Duration),col="BlanchedAlmond")
dev.off()
CairoPNG(width=280,height=325,"/var/www/cgi-bin/bugpandata/startdurxyscatter.png")
plot(DurationValues~DurationStartTimes,data=Duration,col="GoldenRod")
title(main="Scatter Plot for 
start time and associated value")
abline(lm(DurationValues~DurationStartTimes,data=Duration),col="BlanchedAlmond")
dev.off()
CairoPNG(width=280,height=325,"/var/www/cgi-bin/bugpandata/stopdurxyscatter.png")
plot(DurationValues~DurationEndTimes,data=Duration,col="GoldenRod")
title(main="Scatter Plot for 
end time and associated value")
abline(lm(DurationValues~DurationEndTimes,data=Duration),col="BlanchedAlmond")
dev.off()